# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "accd8fd895867b20703cbc0ec49019c0"
name = "ordersExportApp"
handle = "ordersexportapp-1"
application_url = "https://2ccf46156fa2.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,read_all_orders,read_customers,write_metaobjects,read_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://2ccf46156fa2.ngrok-free.app/auth/callback",
  "https://2ccf46156fa2.ngrok-free.app/auth/shopify/callback",
  "https://2ccf46156fa2.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false

[app_preview]
url = "https://example.com/app-preview"
