name: Quarterly Order Processing (Heroku)

# Runs every 3 months on the 1st at 00:00 UTC
on:
  schedule:
    - cron: '0 0 1 */3 *'  # Every 3 months on 1st day at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  process-orders:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Heroku App Webhook
        run: |
          echo "🚀 Triggering quarterly order processing on Heroku..."
          
          # Call your Heroku app's webhook endpoint
          curl -X POST "${{ secrets.APP_URL }}/webhooks/cron/trigger" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "shop=${{ secrets.SHOPIFY_SHOP_DOMAIN }}" \
            --fail \
            --show-error \
            --silent \
            --output response.json
          
          echo "✅ Cron job triggered successfully"
          cat response.json
          
      - name: Notify on Success
        if: success()
        run: |
          echo "🎉 Quarterly processing completed successfully!"
          
      - name: Notify on Failure  
        if: failure()
        run: |
          echo "❌ Quarterly processing failed!"
          # You could add Slack/Discord notifications here

